/**
 * API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmploymentWithDetails } from './employmentWithDetails';
import { Shift } from './shift';


export interface DashboardResponse { 
    shifts: Array<Shift>;
    active_employments: Array<EmploymentWithDetails>;
    total_weekly_hours: number;
    current_shifts: Array<Shift>;
}

