/**
 * API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Employment { 
    id: number;
    user_id: number;
    position_id: number;
    start_date: string;
    end_date?: string | null;
    active: boolean;
    /**
     * 0: exact, 1: quarter_hour, 2: half_hour, 3: custom
     */
    round_mode?: Employment.RoundModeEnum;
    /**
     * Rounding interval in minutes, required if round_mode is custom (3)
     */
    round_interval?: number | null;
    created_at?: string;
    updated_at?: string;
}
export namespace Employment {
    export const RoundModeEnum = {
        Exact: 'exact',
        QuarterHour: 'quarter_hour',
        HalfHour: 'half_hour',
        Custom: 'custom'
    } as const;
    export type RoundModeEnum = typeof RoundModeEnum[keyof typeof RoundModeEnum];
}


