/**
 * API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PositionAttributes } from './positionAttributes';


export interface EmploymentCreateRequestEmployment { 
    position_id?: number;
    start_date?: string;
    end_date?: string | null;
    /**
     * 0: exact, 1: quarter_hour, 2: half_hour, 3: custom
     */
    round_mode?: number;
    /**
     * Rounding interval in minutes, required if round_mode is custom (3)
     */
    round_interval?: number | null;
    position_attributes?: PositionAttributes;
}

