/**
 * API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PositionAttributes } from './positionAttributes';


export interface EmploymentUpdateRequestEmployment { 
    position_id?: number;
    start_date?: string;
    end_date?: string | null;
    position_attributes?: PositionAttributes;
}

