/**
 * API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Shift } from './shift';
import { Company } from './company';
import { Position } from './position';


export interface EmploymentWithDetails { 
    id: number;
    user_id: number;
    position_id: number;
    start_date: string;
    end_date?: string | null;
    active: boolean;
    created_at?: string;
    updated_at?: string;
    position: Position;
    company: Company;
    shifts?: Array<Shift>;
}

