/**
 * API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Shift } from './shift';
import { Employment } from './employment';


export interface Get200Response { 
    shifts: Array<Shift>;
    active_employments: Array<Employment>;
    /**
     * Object where each key is an employment ID (as a string) and each value is the total hours worked that week (float).
     */
    total_weekly_hours: { [key: string]: number; };
    current_shifts: Array<Shift>;
}

