/**
 * API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmploymentWithDetails } from './employmentWithDetails';
import { Shift } from './shift';


export interface Get200Response { 
    shifts: Array<Shift>;
    active_employments: Array<EmploymentWithDetails>;
    /**
     * Object where each key is an employment ID (as a string) and each value is the total hours worked that week (float).
     */
    total_weekly_hours: { [key: string]: number; };
    /**
     * Object where each key is a date and employment ID (format \"YYYY-MM-DD_EMPLOYMENT_ID\") and each value is the total hours worked that day (float).
     */
    daily_hours: { [key: string]: number; };
    current_shifts: Array<Shift>;
}

