/**
 * API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Shift } from './shift';
import { Employment } from './employment';


export interface Get200Response { 
    shifts: Array<Shift>;
    active_employments: Array<Employment>;
    total_weekly_hours: number;
    current_shifts: Array<Shift>;
}

