/**
 * API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HourlyRatesPostRequestHourlyRate { 
    user_position_id: number;
    rate_cents: number;
    effective_date: string;
}

