/**
 * API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HourlyRatesIdPut200Response { 
    id?: number;
    user_position_id?: number;
    rate_cents?: number;
    rate?: string;
    effective_date?: string;
    created_at?: string;
    updated_at?: string;
}

