/**
 * API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HourlyRatesPostRequestHourlyRate } from './hourlyRatesPostRequestHourlyRate';


export interface HourlyRatesPostRequest { 
    hourly_rate: HourlyRatesPostRequestHourlyRate;
}

