/**
 * API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Company } from './company';


export interface Position { 
    id: number;
    title: string;
    company_id: number;
    company?: Company;
    created_at?: string;
    updated_at?: string;
}

