/**
 * API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PositionsIdPut200Response { 
    id?: number;
    title?: string;
    company_id?: number;
    created_at?: string;
    updated_at?: string;
}

