/**
 * API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CompanyAttributes } from './companyAttributes';


export interface PositionAttributes { 
    title: string;
    description?: string;
    remote?: boolean;
    company_attributes: CompanyAttributes;
}

