/**
 * API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProfileResponseUser } from './profileResponseUser';


export interface ProfileResponse { 
    user: ProfileResponseUser;
}

