/**
 * API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Company } from './company';
import { Position } from './position';


export interface ProfileResponseFormData { 
    companies: Array<Company>;
    positions: Array<Position>;
}

