/**
 * API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProfileResponseUserAllOfEmploymentsInner } from './profileResponseUserAllOfEmploymentsInner';


export interface ProfileResponseUser { 
    id: number;
    first_name: string;
    last_name: string;
    username: string;
    email: string;
    name?: string;
    created_at?: string;
    updated_at?: string;
    employments: Array<ProfileResponseUserAllOfEmploymentsInner>;
}

