/**
 * API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Company } from './company';
import { Position } from './position';


export interface ProfileResponseUserAllOfEmploymentsInner { 
    id: number;
    user_id: number;
    position_id: number;
    start_date: string;
    end_date?: string;
    created_at?: string;
    updated_at?: string;
    position: Position;
    company: Company;
}

