/**
 * API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ShiftsIdPatchRequestShift { 
    date?: string;
    start_time?: string;
    end_time?: string | null;
    employment_id?: number;
    description?: string;
}

