/**
 * API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SignInPostRequestUser } from './signInPostRequestUser';


export interface SignInPostRequest { 
    user: SignInPostRequestUser;
}

