/**
 * API V1
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShiftsPostRequestShift } from './ShiftsPostRequestShift';


export interface ShiftsPostRequest {
    shift: ShiftsPostRequestShift;
}
