/**
 * API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TimeEntriesIdPutRequestTimeEntry } from './timeEntriesIdPutRequestTimeEntry';


export interface TimeEntriesIdPutRequest { 
    time_entry: TimeEntriesIdPutRequestTimeEntry;
}

