/**
 * API V1
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ShiftsIdPut200Response {
    id?: number;
    employment_id?: number;
    user_id?: number;
    group_id?: number | null;
    minutes_worked?: number;
    date?: string;
    notes?: string | null;
    created_at?: string;
    updated_at?: string;
}
