/**
 * API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserPositionsIdPutRequestUserPosition } from './userPositionsIdPutRequestUserPosition';


export interface UserPositionsIdPutRequest { 
    user_position: UserPositionsIdPutRequestUserPosition;
}

