# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
Style/StringLiterals:
  Description: 'Use single quotes unless interpolation is needed'
  Enabled: true
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
  ConsistentQuotesInMultiline: true

Style/StringLiteralsInInterpolation:
  Description: 'Use single quotes in interpolated strings unless nested interpolation is needed'
  Enabled: true
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

Layout/SpaceInsideArrayLiteralBrackets:
  Description: 'No spaces inside array brackets'
  Enabled: true
  EnforcedStyle: no_space
  SupportedStyles:
    - space
    - no_space

Layout/MultilineAssignmentLayout:
  Description: 'Align multiline assignments with the keyword, not the variable'
  Enabled: true
  EnforcedStyle: same_line

Layout/CaseIndentation:
  Description: 'Align case statements with the case keyword'
  Enabled: true
  EnforcedStyle: case
  SupportedStyles:
    - case
    - end
  IndentOneStep: false

Layout/EndAlignment:
  Description: 'Align end with the case/if keyword'
  Enabled: true
  EnforcedStyleAlignWith: keyword
  SupportedStylesAlignWith:
    - keyword
    - variable
    - start_of_line
