---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/users":
    get:
      summary: list users
      tags:
      - Users
      description: Retrieve all users
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    first_name:
                      type: string
                      example: John
                    last_name:
                      type: string
                      example: Doe
                    username:
                      type: string
                      example: johndoe
                    email:
                      type: string
                      example: john.doe@example.com
                    created_at:
                      type: string
                      format: date-time
                    updated_at:
                      type: string
                      format: date-time
                  required:
                  - id
                  - first_name
                  - last_name
                  - username
                  - email
    post:
      summary: create user
      tags:
      - Users
      description: Create a new user
      parameters: []
      responses:
        '201':
          description: user created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  first_name:
                    type: string
                    example: John
                  last_name:
                    type: string
                    example: Doe
                  username:
                    type: string
                    example: johndoe
                  email:
                    type: string
                    example: john.doe@example.com
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
        '422':
          description: invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    additionalProperties:
                      type: array
                      items:
                        type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    first_name:
                      type: string
                      example: John
                    last_name:
                      type: string
                      example: Doe
                    username:
                      type: string
                      example: johndoe
                    email:
                      type: string
                      example: john.doe@example.com
                  required:
                  - first_name
                  - last_name
                  - username
                  - email
              required:
              - user
  "/users/{id}":
    parameters:
    - name: id
      in: path
      description: user id
      required: true
      schema:
        type: string
    get:
      summary: show user
      tags:
      - Users
      description: Retrieve a specific user
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  first_name:
                    type: string
                    example: John
                  last_name:
                    type: string
                    example: Doe
                  username:
                    type: string
                    example: johndoe
                  email:
                    type: string
                    example: john.doe@example.com
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
        '404':
          description: user not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: User not found
    patch:
      summary: update user
      tags:
      - Users
      description: Update a user
      parameters: []
      responses:
        '200':
          description: user updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  first_name:
                    type: string
                    example: Jane
                  last_name:
                    type: string
                    example: Smith
                  username:
                    type: string
                    example: janesmith
                  email:
                    type: string
                    example: jane.smith@example.com
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
        '422':
          description: invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    additionalProperties:
                      type: array
                      items:
                        type: string
        '404':
          description: user not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: User not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    first_name:
                      type: string
                      example: Jane
                    last_name:
                      type: string
                      example: Smith
                    username:
                      type: string
                      example: janesmith
                    email:
                      type: string
                      example: jane.smith@example.com
              required:
              - user
    put:
      summary: update user
      tags:
      - Users
      description: Update a user (PUT)
      parameters: []
      responses:
        '200':
          description: user updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  first_name:
                    type: string
                    example: Jane
                  last_name:
                    type: string
                    example: Smith
                  username:
                    type: string
                    example: janesmith
                  email:
                    type: string
                    example: jane.smith@example.com
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    first_name:
                      type: string
                      example: Jane
                    last_name:
                      type: string
                      example: Smith
                    username:
                      type: string
                      example: janesmith
                    email:
                      type: string
                      example: jane.smith@example.com
              required:
              - user
    delete:
      summary: delete user
      tags:
      - Users
      description: Delete a user
      responses:
        '204':
          description: user deleted
        '404':
          description: user not found
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
