---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/sign_in":
    post:
      summary: sign in user
      tags:
      - Authentication
      description: Authenticate user and create session
      parameters: []
      responses:
        '200':
          description: successful authentication
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/LoginResponse"
        '401':
          description: invalid credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: string
                    example:
                    - Invalid email or password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                      example: user@example.com
                    password:
                      type: string
                      example: password123
                  required:
                  - email
                  - password
              required:
              - user
  "/sign_out":
    delete:
      summary: sign out user
      tags:
      - Authentication
      description: Destroy user session
      responses:
        '200':
          description: successful logout
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Logged out successfully
  "/":
    get:
      summary: show dashboard
      tags:
      - Dashboard
      description: Retrieve dashboard data including active employments, shifts, total
        weekly hours, and current shifts
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  shifts:
                    type: array
                    items:
                      "$ref": "#/components/schemas/Shift"
                  active_employments:
                    type: array
                    items:
                      "$ref": "#/components/schemas/EmploymentWithDetails"
                  total_weekly_hours:
                    type: object
                    description: Object where each key is an employment ID (as a string)
                      and each value is the total hours worked that week (float).
                    additionalProperties:
                      type: number
                      format: float
                      example: 38.5
                  current_shifts:
                    type: array
                    items:
                      "$ref": "#/components/schemas/Shift"
                required:
                - shifts
                - active_employments
                - total_weekly_hours
                - current_shifts
  "/employments":
    get:
      summary: list employments
      tags:
      - Employments
      description: Get all employments for the current user
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Employment"
        '401':
          description: unauthorized
    post:
      summary: create employment
      tags:
      - Employments
      description: Create a new employment
      parameters: []
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Employment"
        '422':
          description: unprocessable entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: string
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/EmploymentCreateRequest"
  "/employments/{id}":
    parameters:
    - name: id
      in: path
      description: Employment ID
      required: true
      schema:
        type: string
    get:
      summary: show employment
      tags:
      - Employments
      description: Get a specific employment
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Employment"
        '404':
          description: not found
        '401':
          description: unauthorized
    patch:
      summary: update employment
      tags:
      - Employments
      description: Update an employment
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Employment"
        '422':
          description: unprocessable entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: string
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/EmploymentUpdateRequest"
    delete:
      summary: delete employment
      tags:
      - Employments
      description: Delete an employment
      responses:
        '204':
          description: no content
        '404':
          description: not found
        '401':
          description: unauthorized
  "/employments/{id}/clock_in":
    post:
      summary: clock in employment
      tags:
      - Employments
      description: Clock in for a specific employment
      parameters:
      - name: id
        in: path
        description: Employment ID
        required: true
        schema:
          type: string
      responses:
        '201':
          description: successful clock in
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Shift"
        '422':
          description: unprocessable entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: string
        '401':
          description: unauthorized
  "/employments/{id}/clock_out":
    post:
      summary: clock out employment
      tags:
      - Employments
      description: Clock out for a specific employment
      parameters:
      - name: id
        in: path
        description: Employment ID
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful clock out
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Shift"
        '422':
          description: unprocessable entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: string
        '401':
          description: unauthorized
  "/profile":
    get:
      summary: show profile
      tags:
      - Profiles
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ProfileResponse"
        '404':
          description: user not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                - error
    patch:
      summary: update profile
      tags:
      - Profiles
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                - message
        '422':
          description: unprocessable entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: array
                    items:
                      type: string
                required:
                - error
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/ProfileUpdateRequest"
components:
  schemas:
    Company:
      type: object
      properties:
        id:
          type: integer
          example: 60
        name:
          type: string
          example: Rolfson and Sons
        description:
          type: string
          example: Open-source encompassing encoding
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
      - id
      - name
    User:
      type: object
      properties:
        id:
          type: integer
          example: 1
        first_name:
          type: string
          example: Lan
        last_name:
          type: string
          example: Zboncak
        username:
          type: string
          example: maria_oconnell
          minLength: 3
          maxLength: 20
        email:
          type: string
          format: email
          example: kip@terry.test
        name:
          type: string
          example: Christene Mueller
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
      - id
      - first_name
      - last_name
      - username
      - email
    Profile:
      type: object
      properties:
        first_name:
          type: string
          example: Bryan
        last_name:
          type: string
          example: Friesen
        username:
          type: string
          example: nicole
        email:
          type: string
          format: email
          example: jack_jakubowski@conn-batz.test
    AuthenticatedUser:
      type: object
      properties:
        id:
          type: integer
          example: 1
        email:
          type: string
          format: email
          example: beau@skiles-kozey.example
        first_name:
          type: string
          example: Jaimie
        last_name:
          type: string
          example: Marvin
        username:
          type: string
          example: faustina_mcclure
      required:
      - id
      - email
    Employment:
      type: object
      properties:
        id:
          type: integer
          example: 48
        user_id:
          type: integer
          example: 56
        position_id:
          type: integer
          example: 73
        start_date:
          type: string
          format: date
          example: '2025-06-11'
        end_date:
          type: string
          format: date
          nullable: true
          example: '2025-06-18'
        active:
          type: boolean
          example: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
      - id
      - user_id
      - position_id
      - start_date
      - active
    EmploymentWithDetails:
      allOf:
      - "$ref": "#/components/schemas/Employment"
      - type: object
        properties:
          position:
            "$ref": "#/components/schemas/Position"
          company:
            "$ref": "#/components/schemas/Company"
        required:
        - position
        - company
    Position:
      type: object
      properties:
        id:
          type: integer
          example: 21
        title:
          type: string
          example: Regional Government Associate
        description:
          type: string
          example: Reduced 24 hour functionalities
        company_id:
          type: integer
          example: 13
        remote:
          type: boolean
          example: false
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
      - id
      - title
      - company_id
    Shift:
      type: object
      properties:
        id:
          type: integer
          example: 61
        employment_id:
          type: integer
          example: 56
        date:
          type: string
          format: date
          example: '2025-06-02'
        start_time:
          type: string
          format: date-time
          example: '2025-06-05 09:06:49 -0400'
        end_time:
          type: string
          format: date-time
          nullable: true
          example: '2025-06-07 05:54:39 -0400'
        hours:
          type: number
          format: float
          example: 8.41
        active:
          type: boolean
          example: false
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
      - id
      - employment_id
      - date
      - start_time
    ClockInRequest:
      type: object
      properties:
        employment_id:
          type: integer
          description: ID of the employment to clock in for
      required:
      - employment_id
    ClockOutRequest:
      type: object
      properties:
        employment_id:
          type: integer
          description: ID of the employment to clock out of
      required:
      - employment_id
    DashboardResponse:
      type: object
      properties:
        shifts:
          type: array
          items:
            "$ref": "#/components/schemas/Shift"
        active_employments:
          type: array
          items:
            "$ref": "#/components/schemas/EmploymentWithDetails"
        total_weekly_hours:
          type: object
          description: Object where each key is an employment ID (as a string) and
            each value is the total hours worked that week (float).
          additionalProperties:
            type: number
            format: float
            example: 38.5
        current_shifts:
          type: array
          items:
            "$ref": "#/components/schemas/Shift"
      required:
      - shifts
      - active_employments
      - total_weekly_hours
      - current_shifts
    UserCreateRequest:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        username:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
        password_confirmation:
          type: string
      required:
      - first_name
      - last_name
      - username
      - email
      - password
      - password_confirmation
    UserUpdateRequest:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        username:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
        password_confirmation:
          type: string
      required: []
    LoginResponse:
      type: object
      properties:
        user:
          "$ref": "#/components/schemas/AuthenticatedUser"
      required:
      - user
    CreateComponyRequest:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
      required:
      - name
    UpdateCompanyRequest:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
      required: []
    ProfileResponse:
      type: object
      properties:
        user:
          allOf:
          - "$ref": "#/components/schemas/User"
          - type: object
            properties:
              employments:
                type: array
                items:
                  allOf:
                  - "$ref": "#/components/schemas/Employment"
                  - type: object
                    properties:
                      position:
                        "$ref": "#/components/schemas/Position"
                      company:
                        "$ref": "#/components/schemas/Company"
                    required:
                    - position
                    - company
            required:
            - employments
      required:
      - user
    ProfileUpdateRequest:
      type: object
      properties:
        profile:
          "$ref": "#/components/schemas/Profile"
      required:
      - profile
    CompanyAttributes:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
      required:
      - name
    PositionAttributes:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        remote:
          type: boolean
        company_attributes:
          "$ref": "#/components/schemas/CompanyAttributes"
      required:
      - title
      - company_attributes
    EmploymentCreateRequest:
      type: object
      properties:
        employment:
          type: object
          properties:
            position_id:
              type: integer
            start_date:
              type: string
              format: date
            end_date:
              type: string
              format: date
              nullable: true
            position_attributes:
              "$ref": "#/components/schemas/PositionAttributes"
          anyOf:
          - required:
            - position_id
            - start_date
          - required:
            - position_attributes
            - start_date
      required:
      - employment
    EmploymentUpdateRequest:
      type: object
      properties:
        employment:
          type: object
          properties:
            position_id:
              type: integer
            start_date:
              type: string
              format: date
            end_date:
              type: string
              format: date
              nullable: true
            position_attributes:
              "$ref": "#/components/schemas/PositionAttributes"
      required:
      - employment
servers:
- url: http://localhost:3000
  description: Development server
- url: https://api.nmd98.com
  description: Production server
