---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/sign_in":
    post:
      summary: sign in user
      tags:
      - Authentication
      description: Authenticate user and create session
      parameters: []
      responses:
        '200':
          description: successful authentication
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/LoginResponse"
        '401':
          description: invalid credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: string
                    example:
                    - Invalid email or password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                      example: user@example.com
                    password:
                      type: string
                      example: password123
                  required:
                  - email
                  - password
              required:
              - user
  "/sign_out":
    delete:
      summary: sign out user
      tags:
      - Authentication
      description: Destroy user session
      responses:
        '200':
          description: successful logout
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Logged out successfully
  "/":
    get:
      summary: show dashboard
      tags:
      - Dashboard
      description: Retrieve dashboard data including active employments, shifts, total
        weekly hours, and current shifts
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  shifts:
                    type: array
                    items:
                      "$ref": "#/components/schemas/Shift"
                  active_employments:
                    type: array
                    items:
                      "$ref": "#/components/schemas/Employment"
                  total_weekly_hours:
                    type: number
                    format: float
                  current_shifts:
                    type: array
                    items:
                      "$ref": "#/components/schemas/Shift"
                required:
                - shifts
                - active_employments
                - total_weekly_hours
                - current_shifts
components:
  schemas:
    Company:
      type: object
      properties:
        id:
          type: integer
          example: 21
        name:
          type: string
          example: Mayer Group
        description:
          type: string
          example: Self-enabling multi-tasking open architecture
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
      - id
      - name
    User:
      type: object
      properties:
        id:
          type: integer
          example: 1
        first_name:
          type: string
          example: Sunday
        last_name:
          type: string
          example: Turner
        username:
          type: string
          example: caridad.bechtelar
        email:
          type: string
          example: vincent@hoppe.example
        name:
          type: string
          example: Alton Stoltenberg DC
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
      - id
      - first_name
      - last_name
      - username
      - email
    AuthenticatedUser:
      type: object
      properties:
        id:
          type: integer
          example: 1
        email:
          type: string
          example: chloe_jaskolski@hartmann.example
        first_name:
          type: string
          example: Shante
        last_name:
          type: string
          example: Koch
        username:
          type: string
          example: denny
      required:
      - id
      - email
    Employment:
      type: object
      properties:
        id:
          type: integer
          example: 89
        user_id:
          type: integer
          example: 50
        position_id:
          type: integer
          example: 85
        start_date:
          type: string
          format: date
          example: '2025-05-16'
        end_date:
          type: string
          format: date
          example: '2025-06-28'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
      - id
      - user_id
      - position_id
      - start_date
    Position:
      type: object
      properties:
        id:
          type: integer
          example: 49
        title:
          type: string
          example: Product Design Engineer
        description:
          type: string
          example: User-friendly interactive internet solution
        company_id:
          type: integer
          example: 57
        remote:
          type: boolean
          example: false
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
      - id
      - title
      - company_id
    Shift:
      type: object
      properties:
        id:
          type: integer
          example: 21
        employment_id:
          type: integer
          example: 78
        date:
          type: string
          format: date
          example: '2025-05-18'
        start_time:
          type: string
          format: date-time
          example: '2025-05-20 10:17:22 -0400'
        end_time:
          type: string
          format: date-time
          example: '2025-05-29 17:30:14 -0400'
        hours:
          type: number
          format: float
          example: 0.21
        active:
          type: boolean
          example: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
      - id
      - employment_id
      - date
      - start_time
    UserCreateRequest:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        username:
          type: string
        email:
          type: string
        password:
          type: string
        password_confirmation:
          type: string
      required:
      - first_name
      - last_name
      - username
      - email
      - password
      - password_confirmation
    UserUpdateRequest:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        username:
          type: string
        email:
          type: string
        password:
          type: string
        password_confirmation:
          type: string
      required: []
    LoginResponse:
      type: object
      properties:
        user:
          "$ref": "#/components/schemas/AuthenticatedUser"
      required:
      - user
    CreateComponyRequest:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
      required:
      - name
    UpdateCompanyRequest:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
      required: []
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
