export * from './authentication.service';
import { AuthenticationService } from './authentication.service';
export * from './authentication.serviceInterface';
export * from './companies.service';
import { CompaniesService } from './companies.service';
export * from './companies.serviceInterface';
export * from './groups.service';
import { GroupsService } from './groups.service';
export * from './groups.serviceInterface';
export * from './hourlyRates.service';
import { HourlyRatesService } from './hourlyRates.service';
export * from './hourlyRates.serviceInterface';
export * from './positions.service';
import { PositionsService } from './positions.service';
export * from './positions.serviceInterface';
export * from './timeEntries.service';
import { TimeEntriesService } from './timeEntries.service';
export * from './timeEntries.serviceInterface';
export * from './userPositions.service';
import { UserPositionsService } from './userPositions.service';
export * from './userPositions.serviceInterface';
export * from './users.service';
import { UsersService } from './users.service';
export * from './users.serviceInterface';
export const APIS = [AuthenticationService, CompaniesService, GroupsService, HourlyRatesService, PositionsService, TimeEntriesService, UserPositionsService, UsersService];
