export * from './authentication.service';
import { AuthenticationService } from './authentication.service';
export * from './authentication.serviceInterface';
export * from './dashboard.service';
import { DashboardService } from './dashboard.service';
export * from './dashboard.serviceInterface';
export * from './employments.service';
import { EmploymentsService } from './employments.service';
export * from './employments.serviceInterface';
export * from './profiles.service';
import { ProfilesService } from './profiles.service';
export * from './profiles.serviceInterface';
export * from './shifts.service';
import { ShiftsService } from './shifts.service';
export * from './shifts.serviceInterface';
export const APIS = [AuthenticationService, DashboardService, EmploymentsService, ProfilesService, ShiftsService];
