/**
 * API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { LoginResponse } from '../model/models';
import { SignInPost401Response } from '../model/models';
import { SignInPostRequest } from '../model/models';
import { SignOutDelete200Response } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AuthenticationServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * sign in user
     * Authenticate user and create session
     * @param signInPostRequest 
     */
    signInPost(signInPostRequest?: SignInPostRequest, extraHttpRequestParams?: any): Observable<LoginResponse>;

    /**
     * sign out user
     * Destroy user session
     */
    signOutDelete(extraHttpRequestParams?: any): Observable<SignOutDelete200Response>;

}
