/**
 * API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CompaniesGet200ResponseInner } from '../model/models';
import { CompaniesIdGet404Response } from '../model/models';
import { CompaniesIdPut200Response } from '../model/models';
import { CompaniesIdPutRequest } from '../model/models';
import { CompaniesPost201Response } from '../model/models';
import { CompaniesPost422Response } from '../model/models';
import { CompaniesPostRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface CompaniesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * list companies
     * Retrieve all companies
     */
    companiesGet(extraHttpRequestParams?: any): Observable<Array<CompaniesGet200ResponseInner>>;

    /**
     * delete company
     * Delete a company
     * @param id company id
     */
    companiesIdDelete(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * show company
     * Retrieve a specific company
     * @param id company id
     */
    companiesIdGet(id: string, extraHttpRequestParams?: any): Observable<CompaniesPost201Response>;

    /**
     * update company
     * Update a company
     * @param id company id
     * @param companiesIdPutRequest 
     */
    companiesIdPatch(id: string, companiesIdPutRequest?: CompaniesIdPutRequest, extraHttpRequestParams?: any): Observable<CompaniesIdPut200Response>;

    /**
     * update company
     * Update a company (PUT)
     * @param id company id
     * @param companiesIdPutRequest 
     */
    companiesIdPut(id: string, companiesIdPutRequest?: CompaniesIdPutRequest, extraHttpRequestParams?: any): Observable<CompaniesIdPut200Response>;

    /**
     * create company
     * Create a new company
     * @param companiesPostRequest 
     */
    companiesPost(companiesPostRequest?: CompaniesPostRequest, extraHttpRequestParams?: any): Observable<CompaniesPost201Response>;

}
