/**
 * API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Get200Response } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface DashboardServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * show dashboard
     * Retrieve dashboard data including active employments, shifts, total weekly hours, and current shifts
     */
    rootGet(extraHttpRequestParams?: any): Observable<Get200Response>;

}
