/**
 * API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CompaniesPost422Response } from '../model/models';
import { GroupsGet200ResponseInner } from '../model/models';
import { GroupsIdGet404Response } from '../model/models';
import { GroupsIdPut200Response } from '../model/models';
import { GroupsIdPutRequest } from '../model/models';
import { GroupsPost201Response } from '../model/models';
import { GroupsPostRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface GroupsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * list groups
     * Retrieve all groups
     */
    groupsGet(extraHttpRequestParams?: any): Observable<Array<GroupsGet200ResponseInner>>;

    /**
     * delete group
     * Delete a group
     * @param id group id
     */
    groupsIdDelete(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * show group
     * Retrieve a specific group
     * @param id group id
     */
    groupsIdGet(id: string, extraHttpRequestParams?: any): Observable<GroupsPost201Response>;

    /**
     * update group
     * Update a group
     * @param id group id
     * @param groupsIdPutRequest 
     */
    groupsIdPatch(id: string, groupsIdPutRequest?: GroupsIdPutRequest, extraHttpRequestParams?: any): Observable<GroupsIdPut200Response>;

    /**
     * update group
     * Update a group (PUT)
     * @param id group id
     * @param groupsIdPutRequest 
     */
    groupsIdPut(id: string, groupsIdPutRequest?: GroupsIdPutRequest, extraHttpRequestParams?: any): Observable<GroupsIdPut200Response>;

    /**
     * create group
     * Create a new group
     * @param groupsPostRequest 
     */
    groupsPost(groupsPostRequest?: GroupsPostRequest, extraHttpRequestParams?: any): Observable<GroupsPost201Response>;

}
