/**
 * API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CompaniesPost422Response } from '../model/models';
import { HourlyRatesGet200ResponseInner } from '../model/models';
import { HourlyRatesIdGet404Response } from '../model/models';
import { HourlyRatesIdPut200Response } from '../model/models';
import { HourlyRatesIdPutRequest } from '../model/models';
import { HourlyRatesPost201Response } from '../model/models';
import { HourlyRatesPostRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface HourlyRatesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * list hourly rates
     * Retrieve all hourly rates
     */
    hourlyRatesGet(extraHttpRequestParams?: any): Observable<Array<HourlyRatesGet200ResponseInner>>;

    /**
     * delete hourly rate
     * Delete an hourly rate
     * @param id hourly rate id
     */
    hourlyRatesIdDelete(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * show hourly rate
     * Retrieve a specific hourly rate
     * @param id hourly rate id
     */
    hourlyRatesIdGet(id: string, extraHttpRequestParams?: any): Observable<HourlyRatesPost201Response>;

    /**
     * update hourly rate
     * Update an hourly rate
     * @param id hourly rate id
     * @param hourlyRatesIdPutRequest 
     */
    hourlyRatesIdPatch(id: string, hourlyRatesIdPutRequest?: HourlyRatesIdPutRequest, extraHttpRequestParams?: any): Observable<HourlyRatesIdPut200Response>;

    /**
     * update hourly rate
     * Update an hourly rate (PUT)
     * @param id hourly rate id
     * @param hourlyRatesIdPutRequest 
     */
    hourlyRatesIdPut(id: string, hourlyRatesIdPutRequest?: HourlyRatesIdPutRequest, extraHttpRequestParams?: any): Observable<HourlyRatesIdPut200Response>;

    /**
     * create hourly rate
     * Create a new hourly rate
     * @param hourlyRatesPostRequest 
     */
    hourlyRatesPost(hourlyRatesPostRequest?: HourlyRatesPostRequest, extraHttpRequestParams?: any): Observable<HourlyRatesPost201Response>;

}
