/**
 * API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CompaniesPost422Response } from '../model/models';
import { Position } from '../model/models';
import { PositionsIdGet404Response } from '../model/models';
import { PositionsIdPutRequest } from '../model/models';
import { PositionsPostRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PositionsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * list positions
     * Retrieve all positions
     */
    positionsGet(extraHttpRequestParams?: any): Observable<Array<Position>>;

    /**
     * delete position
     * Delete a position
     * @param id position id
     */
    positionsIdDelete(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * show position
     * Retrieve a specific position
     * @param id position id
     */
    positionsIdGet(id: string, extraHttpRequestParams?: any): Observable<Position>;

    /**
     * update position
     * Update a position
     * @param id position id
     * @param positionsIdPutRequest 
     */
    positionsIdPatch(id: string, positionsIdPutRequest?: PositionsIdPutRequest, extraHttpRequestParams?: any): Observable<Position>;

    /**
     * update position
     * Update a position (PUT)
     * @param id position id
     * @param positionsIdPutRequest 
     */
    positionsIdPut(id: string, positionsIdPutRequest?: PositionsIdPutRequest, extraHttpRequestParams?: any): Observable<Position>;

    /**
     * create position
     * Create a new position
     * @param positionsPostRequest 
     */
    positionsPost(positionsPostRequest?: PositionsPostRequest, extraHttpRequestParams?: any): Observable<Position>;

}
