/**
 * API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ProfileGet404Response } from '../model/models';
import { ProfileResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ProfilesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * show profile
     * 
     */
    profileGet(extraHttpRequestParams?: any): Observable<ProfileResponse>;

}
