/**
 * API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { EmploymentsPost422Response } from '../model/models';
import { Shift } from '../model/models';
import { ShiftResponse } from '../model/models';
import { ShiftsIdPatch404Response } from '../model/models';
import { ShiftsIdPatchRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ShiftsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * delete shift
     * Delete a shift
     * @param id Shift ID
     */
    shiftsIdDelete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * show shift
     * Show a specific shift
     * @param id Shift ID
     */
    shiftsIdGet(id: number, extraHttpRequestParams?: any): Observable<ShiftResponse>;

    /**
     * update shift
     * Update a shift
     * @param id Shift ID
     * @param shiftsIdPatchRequest 
     */
    shiftsIdPatch(id: number, shiftsIdPatchRequest?: ShiftsIdPatchRequest, extraHttpRequestParams?: any): Observable<Shift>;

}
