/**
 * API V1
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CompaniesPost422Response } from '../model/models';
import { ShiftsGet200ResponseInner } from '../model/models';
import { ShiftsIdGet404Response } from '../model/models';
import { ShiftsIdPut200Response } from '../model/models';
import { ShiftsIdPutRequest } from '../model/models';
import { ShiftsPost201Response } from '../model/models';
import { ShiftsPostRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ShiftsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * list shifts
     * Retrieve all shifts
     */
    ShiftsGet(extraHttpRequestParams?: any): Observable<Array<ShiftsGet200ResponseInner>>;

    /**
     * delete shift
     * Delete a shift
     * @param id shift id
     */
    ShiftsIdDelete(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * show shift
     * Retrieve a specific shift
     * @param id shift id
     */
    ShiftsIdGet(id: string, extraHttpRequestParams?: any): Observable<ShiftsPost201Response>;

    /**
     * update shift
     * Update a shift
     * @param id shift id
     * @param ShiftsIdPutRequest
     */
    ShiftsIdPatch(id: string, ShiftsIdPutRequest?: ShiftsIdPutRequest, extraHttpRequestParams?: any): Observable<ShiftsIdPut200Response>;

    /**
     * update shift
     * Update a shift (PUT)
     * @param id shift id
     * @param ShiftsIdPutRequest
     */
    ShiftsIdPut(id: string, ShiftsIdPutRequest?: ShiftsIdPutRequest, extraHttpRequestParams?: any): Observable<ShiftsIdPut200Response>;

    /**
     * create shift
     * Create a new shift
     * @param ShiftsPostRequest
     */
    ShiftsPost(ShiftsPostRequest?: ShiftsPostRequest, extraHttpRequestParams?: any): Observable<ShiftsPost201Response>;

}
