/**
 * API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CompaniesPost422Response } from '../model/models';
import { TimeEntriesGet200ResponseInner } from '../model/models';
import { TimeEntriesIdGet404Response } from '../model/models';
import { TimeEntriesIdPut200Response } from '../model/models';
import { TimeEntriesIdPutRequest } from '../model/models';
import { TimeEntriesPost201Response } from '../model/models';
import { TimeEntriesPostRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface TimeEntriesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * list time entries
     * Retrieve all time entries
     */
    timeEntriesGet(extraHttpRequestParams?: any): Observable<Array<TimeEntriesGet200ResponseInner>>;

    /**
     * delete time entry
     * Delete a time entry
     * @param id time entry id
     */
    timeEntriesIdDelete(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * show time entry
     * Retrieve a specific time entry
     * @param id time entry id
     */
    timeEntriesIdGet(id: string, extraHttpRequestParams?: any): Observable<TimeEntriesPost201Response>;

    /**
     * update time entry
     * Update a time entry
     * @param id time entry id
     * @param timeEntriesIdPutRequest 
     */
    timeEntriesIdPatch(id: string, timeEntriesIdPutRequest?: TimeEntriesIdPutRequest, extraHttpRequestParams?: any): Observable<TimeEntriesIdPut200Response>;

    /**
     * update time entry
     * Update a time entry (PUT)
     * @param id time entry id
     * @param timeEntriesIdPutRequest 
     */
    timeEntriesIdPut(id: string, timeEntriesIdPutRequest?: TimeEntriesIdPutRequest, extraHttpRequestParams?: any): Observable<TimeEntriesIdPut200Response>;

    /**
     * create time entry
     * Create a new time entry
     * @param timeEntriesPostRequest 
     */
    timeEntriesPost(timeEntriesPostRequest?: TimeEntriesPostRequest, extraHttpRequestParams?: any): Observable<TimeEntriesPost201Response>;

}
