/**
 * API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CompaniesPost422Response } from '../model/models';
import { UsersGet200ResponseInner } from '../model/models';
import { UsersIdGet404Response } from '../model/models';
import { UsersIdPutRequest } from '../model/models';
import { UsersPostRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface UsersServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * list users
     * Retrieve all users
     */
    usersGet(extraHttpRequestParams?: any): Observable<Array<UsersGet200ResponseInner>>;

    /**
     * delete user
     * Delete a user
     * @param id user id
     */
    usersIdDelete(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * show user
     * Retrieve a specific user
     * @param id user id
     */
    usersIdGet(id: string, extraHttpRequestParams?: any): Observable<UsersGet200ResponseInner>;

    /**
     * update user
     * Update a user
     * @param id user id
     * @param usersIdPutRequest 
     */
    usersIdPatch(id: string, usersIdPutRequest?: UsersIdPutRequest, extraHttpRequestParams?: any): Observable<UsersGet200ResponseInner>;

    /**
     * update user
     * Update a user (PUT)
     * @param id user id
     * @param usersIdPutRequest 
     */
    usersIdPut(id: string, usersIdPutRequest?: UsersIdPutRequest, extraHttpRequestParams?: any): Observable<UsersGet200ResponseInner>;

    /**
     * create user
     * Create a new user
     * @param usersPostRequest 
     */
    usersPost(usersPostRequest?: UsersPostRequest, extraHttpRequestParams?: any): Observable<UsersGet200ResponseInner>;

}
