/**
 * API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UsersPostRequestUser } from './usersPostRequestUser';


export interface UsersPostRequest { 
    user: UsersPostRequestUser;
}

